var jobApplicationStates = {
  ARE_YOU_READY_TO_APPLY: {
    yes: 'HAVE_YOU_APPLIED',
    no: 'ARE_YOU_STILL_INTERESTED_IN_PREPARING_TO_APPLYING'
  },
  ARE_YOU_STILL_INTERESTED_IN_PREPARING_TO_APPLYING: {
    yes: 'ARE_YOU_READY_TO_APPLY',
    no: 'NO_LONGER_INTERESTED'
  },

  HAVE_YOU_APPLIED: {
    yes: 'HAVE_YOU_HEARD_BACK_YET',
    no: 'ARE_YOU_STILL_INTERESTED_IN_APPLYING'
  },
  ARE_YOU_STILL_INTERESTED_IN_APPLYING: {
    yes: 'HAVE_YOU_APPLIED',
    no: 'NO_LONGER_INTERESTED'
  },

  HAVE_YOU_HEARD_BACK_YET: {
    yes: 'DO_YOU_HAVE_AN_INTERVIEW',
    no: 'ARE_YOU_STILL_INTERESTED_IN_HEARING_BACK'
  },
  ARE_YOU_STILL_INTERESTED_IN_HEARING_BACK: {
    yes: 'HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_HEADING_BACK',
    no: 'NO_LONGER_INTERESTED'
  },
  HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_HEADING_BACK: {
    yes: 'HAVE_YOU_HEARD_BACK_YET',
    no: 'ARE_YOU_STILL_INTERESTED_IN_HEARING_BACK'
  },

  DO_YOU_HAVE_AN_INTERVIEW: {
    yes: 'ARE_YOU_READY_FOR_YOUR_INTERVIEW',
    no: 'ARE_YOU_STILL_INTERESTED_IN_SCHEDULING_AN_INTERVIEW'
  },
  ARE_YOU_STILL_INTERESTED_IN_SCHEDULING_AN_INTERVIEW: {
    yes: 'HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_SCHEDULING_AN_INTERVIEW',
    no: 'NO_LONGER_INTERESTED'
  },
  HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_SCHEDULING_AN_INTERVIEW: {
    yes: 'DO_YOU_HAVE_AN_INTERVIEW',
    no: 'ARE_YOU_STILL_INTERESTED_IN_SCHEDULING_AN_INTERVIEW'
  },

  ARE_YOU_READY_FOR_YOUR_INTERVIEW: {
    yes: 'HAVE_YOU_HAD_THE_INTERVIEW',
    no: 'ARE_YOU_READY_FOR_YOUR_INTERVIEW'
  },

  HAVE_YOU_HAD_THE_INTERVIEW: {
    yes: 'HAVE_YOU_RECEIVED_A_JOB_OFFER',
    no: 'HAVE_YOU_HAD_THE_INTERVIEW'
  },

  HAVE_YOU_RECEIVED_A_JOB_OFFER: {
    yes: 'SUCCESS',
    no: 'ARE_YOU_STILL_INTERESTED_IN_RECEIVING_AN_OFFER'
  },
  ARE_YOU_STILL_INTERESTED_IN_RECEIVING_AN_OFFER: {
    yes: 'HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_RECEIVING_AN_OFFER',
    no: 'NO_LONGER_INTERESTED'
  },
  HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_RECEIVING_AN_OFFER: {
    yes: 'HAVE_YOU_RECEIVED_A_JOB_OFFER',
    no: 'ARE_YOU_STILL_INTERESTED_IN_RECEIVING_AN_OFFER'
  },

  SUCCESS: {},

  NO_LONGER_INTERESTED: {}
};

module.exports = jobApplicationStates;
