var jobApplicationStates = {
  HAVE_YOU_DONE_EVERYTHING_YOU_NEED_TO_APPLY: {
    yes: 'HAVE_YOU_APPLIED',
    no: 'ARE_YOU_STILL_INTERESTED_IN_PREPARING_TO_APPLYING'
  },
  ARE_YOU_STILL_INTERESTED_IN_PREPARING_TO_APPLYING: {
    yes: 'HAVE_YOU_DONE_EVERYTHING_YOU_NEED_TO_APPLY',
    no: 'ABANDONED'
  },

  HAVE_YOU_APPLIED: {
    yes: 'HAVE_YOU_HEARD_BACK_YET',
    no: 'ARE_YOU_STILL_INTERESTED_IN_APPLYING'
  },
  ARE_YOU_STILL_INTERESTED_IN_APPLYING: {
    yes: 'HAVE_YOU_APPLIED',
    no: 'ABANDONED'
  },

  HAVE_YOU_HEARD_BACK_YET: {
    yes: 'HAVE_YOU_SCHEDULED_AN_INTERVIEW',
    no: 'ARE_YOU_STILL_INTERESTED_IN_HEARING_BACK'
  },
  ARE_YOU_STILL_INTERESTED_IN_HEARING_BACK: {
    yes: 'HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_HEADING_BACK',
    no: 'ABANDONED'
  },
  HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_HEADING_BACK: {
    yes: 'HAVE_YOU_HEARD_BACK_YET',
    no: 'ARE_YOU_STILL_INTERESTED_IN_HEARING_BACK'
  },

  HAVE_YOU_SCHEDULED_AN_INTERVIEW: {
    yes: 'ARE_YOU_READY_FOR_YOUR_INTERVIEW',
    no: 'ARE_YOU_STILL_INTERESTED_IN_SCHEDULING_AN_INTERVIEW'
  },
  ARE_YOU_STILL_INTERESTED_IN_SCHEDULING_AN_INTERVIEW: {
    yes: 'HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_SCHEDULING_AN_INTERVIEW',
    no: 'ABANDONED'
  },
  HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_SCHEDULING_AN_INTERVIEW: {
    yes: 'HAVE_YOU_SCHEDULED_AN_INTERVIEW',
    no: 'ARE_YOU_STILL_INTERESTED_IN_SCHEDULING_AN_INTERVIEW'
  },

  ARE_YOU_READY_FOR_YOUR_INTERVIEW: {
    yes: 'HAVE_YOU_INTERVIEWED_YET',
    no: 'ARE_YOU_READY_FOR_YOUR_INTERVIEW'
  },

  HAVE_YOU_INTERVIEWED_YET: {
    yes: 'HAVE_YOU_RECEIVED_AN_OFFER',
    no: 'HAVE_YOU_INTERVIEWED_YET'
  },

  HAVE_YOU_RECEIVED_AN_OFFER: {
    yes: 'SUCCEEDED',
    no: 'ARE_YOU_STILL_INTERESTED_IN_RECEIVING_AN_OFFER'
  },
  ARE_YOU_STILL_INTERESTED_IN_RECEIVING_AN_OFFER: {
    yes: 'HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_RECEIVING_AN_OFFER',
    no: 'ABANDONED'
  },
  HAVE_YOU_TRIED_FOLLOWING_UP_ABOUT_RECEIVING_AN_OFFER: {
    yes: 'HAVE_YOU_RECEIVED_AN_OFFER',
    no: 'ARE_YOU_STILL_INTERESTED_IN_RECEIVING_AN_OFFER'
  },

  SUCCEEDED: {},

  ABANDONED: {}
};

module.exports = jobApplicationStates;
